# Generated by Django 3.1.3 on 2020-12-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventerapp', '0003_auto_20201202_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='displayName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendees',
            name='emailId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='attachmentLink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='createdBy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='hangoutLink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='organizedBy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reminders',
            name='method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reminders',
            name='minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
